# Generated by Django 3.2.2 on 2023-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnkapp', '0005_auto_20230220_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=50),
        ),
    ]
